version: '3.9'

services:
  db:
    image: postgres:15.3-alpine3.17
    restart: always
    container_name: World3D-db
    environment:
      POSTGRES_DB: World3D
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Forcall80
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres_data: 